name: linting, testing, building
on:
  push:
    branches: [ add-playwright ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v4

      # 1. Запускаем проект на вашей обязательной Node.js 17
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting typescript
        run: npm run lint:ts

      - name: linting css
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit

      - name: build storybook
        run: npm run storybook:build

      # 2. Устанавливаем системный Chromium через APT
      - name: Install Chromium via APT
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      # 3. ВРЕМЕННО переключаем Node.js на v18 исключительно для запуска Playwright
      - name: Switch to Node.js 18 for Playwright
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 4. Запускаем тесты (теперь они гарантированно пройдут проверку версии)
      - name: screenshot testing
        env:
            PLAYWRIGHT_CHROMIUM_HEADLESS_SHELL_EXECUTABLE_PATH: /usr/bin/chromium-browser
        run: npm run test:ui:ci