name: linting, testing, building
on:
  push:
    branches: [ add-playwright ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-22.04

    # Запускаем пайплайн внутри готового окружения со всеми библиотеками Linux
    container:
      image: ://microsoft.com

    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      # Обновлено до v4 для стабильной работы в контейнерах
      - uses: actions/checkout@v4

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # Обновлено до v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Включено кэширование для ускорения последующих запусков

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      - name: linting typescript
        run: npm run lint:ts

      - name: linting css
        run: npm run lint:scss

      - name: unit testing
        run: npm run test:unit

      - name: build storybook
        run: npm run storybook:build

      # ШАГИ УСТАНОВКИ БРАУЗЕРОВ И APT-GET УДАЛЕНЫ (они уже есть в контейнере)

      - name: screenshot testing
        run: npm run test:ui:ci